AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Project02-SpeakTracker

  Sample SAM Template for Project02-SpeakTracker

  '
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java21
    Architectures:
      - x86_64

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /hello
            Method: get
    Metadata:
      SamResourceId: HelloWorldFunction
  TutorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TutorFunction
      Handler: tutor.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor/students
            Method: get
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor/students/{email}
            Method: get
        API3:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor/students/{email}/history
            Method: get
        API4:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor/feedback
            Method: post
    Metadata:
      SamResourceId: TutorFunction
  SessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SessionFunction
      Handler: session.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/sessions/start
            Method: post
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/sessions/end
            Method: post
        API3:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/sessions/history
            Method: get
    Metadata:
      SamResourceId: SessionFunction
  SentencesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SentencesFunction
      Handler: sentences.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/sentences
            Method: get
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/sentences/{id}/audio
            Method: get
    Metadata:
      SamResourceId: SentencesFunction
  TutorRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: TutorRegisterFunction
      Handler: tutorRegister.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor-register
            Method: get
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor-register/{email}/request
            Method: post
        API3:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor-register/requests/{id}/approve
            Method: post
        API4:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/tutor-register/requests/{id}/reject
            Method: post
    Metadata:
      SamResourceId: TutorRegisterFunction
  StatisticsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StatisticsFunction
      Handler: statistics.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/statistics/today
            Method: get
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/statistics/weekly
            Method: get
    Metadata:
      SamResourceId: StatisticsFunction
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: AuthFunction
      Handler: auth.App::handleRequest
      Events:
        API1:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/auth/register
            Method: post
        API2:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/auth/login
            Method: post
        API3:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /api/auth
            Method: get

    Metadata:
      SamResourceId: AuthFunction

  SentencesWebSocketFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SentencesWebSocketFunction
      Handler: websocket.App::handleRequest
    Metadata:
      SamResourceId: SentencesWebSocketFunction


  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors: '''*'''

  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SpeakTrackerWebSocketAPI
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action

  # Lambda 실행 권한
  WebSocketLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SentencesWebSocketFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'

  # Lambda Integration
  WebSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SentencesWebSocketFunction.Arn}/invocations'



  # $connect Route
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      Target: !Sub 'integrations/${WebSocketIntegration}'

  # $disconnect Route
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Sub 'integrations/${WebSocketIntegration}'

  # $default Route
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $default
      Target: !Sub 'integrations/${WebSocketIntegration}'

  # Stage
  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Dev
      ApiId: !Ref WebSocketApi
      AutoDeploy: true

  # Lambda에 WebSocket 연결 관리 권한 부여
  WebSocketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: WebSocketManageConnectionsPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'execute-api:ManageConnections'
            Resource:
              - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketApi}/*'
      Roles:
        - !Ref SentencesWebSocketFunctionRole


Outputs:
  ApiEndpoint:
    Description: API Gateway Base URL
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev
  HelloWorldUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/hello
  TutorsListUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/api/tutors
  SessionsUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/api/sessions
  SentencesUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/api/sentences
  StatisticsUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/api/statistics
  AuthUrl:
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/api/auth

  WebSocketURL:
    Description: WebSocket API URL
    Value: !Sub 'wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/Dev'